---

motion_configuration:
  - "width 720"
  - "height 480"
  - "framerate 15"
  - "quality 50"
  - "pre_capture 0"
  - "post_capture 5"
  - "daemon on"
  - "stream_localhost off"
  - "webcontrol_localhost on"
  - "target_dir /motion"
  - "logfile /motion/motion.log"
  - "process_id_file /motion/motion.pid"
