---

motion_configuration:
  - "width 720"
  - "height 480"
  - "framerate 15"
  - "quality 50"
  - "pre_capture 0"
  - "post_capture 5"
  - "daemon on"
  - "stream_localhost off"
  - "webcontrol_localhost on"
  - "target_dir /motion"
  - "logfile /motion/motion.log"
  - "process_id_file /motion/motion.pid"
  - auto_brightness off
  - brightness 0
  - contrast 0
  - daemon on
  - despeckle_filter EedDl
  - emulate_motion off
  - event_gap 60
  - ffmpeg_bps 400000
  - ffmpeg_duplicate_frames true
  - ffmpeg_output_debug_movies off
  - ffmpeg_output_movies on
  - ffmpeg_timelapse 0
  - ffmpeg_timelapse_mode daily
  - ffmpeg_variable_bitrate 0
  - ffmpeg_video_codec mpeg4
  - framerate 15
  - frequency 0
  - hue 0
  - input -1
  - ipv6_enabled off
  - lightswitch 0
  - locate_motion_mode off
  - locate_motion_style box
  - log_level 6
  - log_type all
  - max_movie_time 0
  - minimum_frame_time 0
  - minimum_motion_frames 1
  - motion_configuration
  - motion_configuration.items
  - movie_filename %v-%Y%m%d%H%M%S
  - netcam_keepalive off
  - netcam_tolerant_check off
  - noise_level 32
  - noise_tune on
  - norm 0
  - output_debug_pictures off
  - output_pictures on
  - picture_filename %v-%Y%m%d%H%M%S-%q
  - picture_type jpeg
  - power_line_frequency -1
  - quiet on
  - rotate 0
  - roundrobin_frames 1
  - roundrobin_skip 1
  - rtsp_uses_tcp on
  - saturation 0
  - setup_mode off
  - smart_mask_speed 0
  - snapshot_filename %v-%Y%m%d%H%M%S-snapshot
  - snapshot_interval 0
  - stream_auth_method 0
  - stream_limit 0
  - stream_localhost off
  - stream_localhost on
  - stream_maxrate 1
  - stream_motion off
  - stream_port 8081
  - stream_quality 50
  - switchfilter off
  - text_changes off
  - text_double off
  - text_event %Y%m%d%H%M%S
  - text_right %Y-%m-%d\n%T-%q
  - threshold 1500
  - threshold_tune off
  - timelapse_filename %Y%m%d-timelapse
  - track_auto off
  - track_iomojo_id 0
  - track_move_wait 10
  - track_speed 255
  - track_step_angle_x 10
  - track_step_angle_y 10
  - track_stepsize 40
  - track_type 0
  - use_extpipe off
  - v4l2_palette 17
  - videodevice /dev/video0
  - webcontrol_html_output on
  - webcontrol_port 8080
